### ISSUE TITLE
Use a variable in a .rouge template

### ISSUE THREAD

**Issue by jankeesvw** [jacobsimeon/rouge-rails#1]
Is it possible to use ERB or something else in a .rouge template?

**Comment by jacobsimeon** [comment]
You should be able to, just make sure to name your partial with the additional .erb extension. 
For example "_my_code_sample.rouge.erb"

**Comment by jacobsimeon** [comment]
Ha, my suggestion doesn't work. Not even close.

I added support for ERB in [version 0.2.1][commit]

[commit]: https://github.com/jacobsimeon/rouge-rails/commit/2678e3b5dec73d31ba967cb872cf0f196beccd0e

**Comment by jacobsimeon** [comment]
@jankeesvw would you mind giving this a try and letting me know if it works for your use case?

**Comment by jankeesvw** [comment]
I just installed version 0.2.1 of this gem, when using a partial that ends in `.rouge.erb` I get this error:

```
ActionView::MissingTemplate at /api/documentation
Missing partial api/documentation/_all_clients_json, application/_all_clients_json with {:locale=>[:nl], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :axlsx, :coffee, :arb, :haml, :jbuilder, :rouge]}. Searched in:
  * "/Users/jankeesvw/Documents/timi/timi/app/views"
  * "/Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activeadmin-1.0.0.pre2/app/views"
  * "/Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/kaminari-0.16.3/app/views"
  * "/Users/jankeesvw/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/devise-3.5.6/app/views"

**Comment by jacobsimeon** [comment]
@jenkeesvw, the update doesn't require a change to the file extension to support ERB, you can leave it as just plain .rouge.

**Comment by jankeesvw** [comment]
:ok_hand: feature confirmed @jacobsimeon, thanks for the work.
