### ISSUE TITLE
Indentation issue

### ISSUE THREAD

**Issue by jankeesvw** [jacobsimeon/rouge-rails#2]
When I render a `rouge` partial from `erb` I see an indentation issue:

![image](https://cloud.githubusercontent.com/assets/167882/14406158/dd2dc11c-fe9f-11e5-8f58-4f0b0a600d1f.png)

This is the `rouge` template:

```json
{
  "message": "unauthorized"
}
```

You can see a preview of this behaviour at: http://timi.dev/api/documentation/#authenticatie

**Comment by jacobsimeon** [comment]
@jankeesvw I haven't been able to get the link to work. I tried rendering that template in a dummy app but wasn't able to reproduce the problem.

Can you paste the code that calls `render` with the rouge template?

**Comment by jankeesvw** [comment]
This is a (simplified)  erb template:

``` erb
<section class="question" id="klanten">
  <h3>Klanten</h3>
  <p>Doormiddel van deze call haal je klanten op die de gebruiker op. Een voorbeeld:</p>

  <h5 class="api-call">GET /api/v1/clients.json</h5>
  <p>Je krijgt dan een JSON resultaat wat er als volgt uit ziet:</p>

  <%= render "all_clients_json", language: :javascript %>
</section>
```

And this is the `_all_clients_json.rouge`:

``` json
[
  {
    "id": 618,
    "name": "Klant A",
    "projects": [
      {
        "id": 3327,
        "name": "Banners",
        "aliases": [
          "Erik",
          "Martijn",
          "Wilco"
        ]
      }
    ]
  }
]
```

**Comment by jacobsimeon** [comment]
@jankeesvw do you think this could be due to something in your CSS? I dropped your markup and partial into a dummy app and still can't reproduce.

Here's a screenshot of what I'm seeing:
<img width="687" alt="screen shot 2016-04-17 at 5 05 42 pm" src="https://cloud.githubusercontent.com/assets/323541/14590725/e576936a-04be-11e6-8020-5e15a6946dd2.png">

**Comment by jankeesvw** [comment]
Weird, if you inspect the CSS on https://timiapp.com/api/documentation do you see anything that's wrong? I'm using `default_colorscheme = "default"`

**Comment by jvenezia** [comment]
Hi @jankeesvw. Seems like you don't have this issue anymore.

I found the solution here: https://github.com/middleman/middleman-syntax/issues/24

**Comment by jankeesvw** [comment]
Okay, I haven't looked at this issue anymore. I'm going to close it, thanks for the help @jvenezia and @jacobsimeon! ✨
